# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./host
# Target is an application:  ../bin/qhost

LIBS += -lpieces \
-lOpenThreads
TARGET = ../bin/qhost
CONFIG += release \
warn_on
TEMPLATE = app
