# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/qchat

HEADERS += chatwidget.h \
           global.h \
           chatpeer.h 
SOURCES += qchat.cpp \
           chatwidget.cpp \
           chatpeer.cpp 
LIBS += -lpieces \
        -lOpenThreads 
TARGET = ../bin/qchat 
CONFIG += release \
          warn_on 
TEMPLATE = app 
